### ISSUE TITLE
Mobile Safari latest bug

### ISSUE THREAD

**Issue by Widdershin** [cyclejs-community/built-with-cycle#2]
![screen](https://files.gitter.im/cyclejs/cycle-core/6ARa/IMG_5310.PNG)

As reported by @cmdv.

ios 9.2

**Comment by Widdershin** [comment]
I can reproduce this in my iOS emulator, from looking through the flex bugs repo it seems like I might just need to put a flex-basis on everything.

**Comment by Cmdv** [comment]
Ah sweet totally forgot to look into this!! Apple are becoming the new Microsoft!
